DROP TABLE IF EXISTS Product;

CREATE TABLE Product (
    id BIGINT(19) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NULL DEFAULT NULL,
    price INT(10) NOT NULL,
    PRIMARY KEY (id) USING BTREE
)